//! Built-in IR simulator.
//!
//! Combinational modules produce truth tables when practical. Sequential
//! modules run for a configurable number of ticks and can be exported as VCD.

use crate::ast::{BinaryOp, Edge, Expr, UnaryOp};
use crate::diagnostic::{Diagnostic, Result};
use crate::ir::{IrModule, IrSignalKind};
use std::collections::{BTreeMap, BTreeSet};
use std::fmt;

/// Simulation options.
#[derive(Clone, Debug)]
pub struct SimOptions {
    /// Number of ticks for sequential simulation.
    pub ticks: usize,
    /// Input overrides keyed by signal name.
    pub inputs: BTreeMap<String, u128>,
}

impl Default for SimOptions {
    fn default() -> Self {
        Self {
            ticks: 8,
            inputs: BTreeMap::new(),
        }
    }
}

/// Result of running the simulator.
#[derive(Clone, Debug)]
pub enum SimulationResult {
    /// Truth table for a combinational module.
    TruthTable(TruthTable),
    /// Waveform for a sequential module.
    Waveform(Waveform),
}

/// Truth table simulation result.
#[derive(Clone, Debug)]
pub struct TruthTable {
    /// Input names in display order.
    pub inputs: Vec<String>,
    /// Output names in display order.
    pub outputs: Vec<String>,
    /// Rows containing signal values keyed by name.
    pub rows: Vec<BTreeMap<String, u128>>,
}

/// Tick-by-tick waveform simulation result.
#[derive(Clone, Debug)]
pub struct Waveform {
    /// Simulated module name.
    pub module_name: String,
    /// Number of simulated ticks.
    pub ticks: usize,
    /// Signal names in display order.
    pub names: Vec<String>,
    /// Signal widths keyed by name.
    pub widths: BTreeMap<String, u32>,
    /// Per-signal value history.
    pub values: BTreeMap<String, Vec<u128>>,
}

/// Run the simulator on an IR module.
pub fn run(module: &IrModule, options: &SimOptions) -> Result<SimulationResult> {
    validate_inputs(module, &options.inputs)?;

    if module.processes.is_empty() {
        Ok(SimulationResult::TruthTable(run_truth_table(
            module, options,
        )?))
    } else {
        Ok(SimulationResult::Waveform(run_waveform(module, options)?))
    }
}

/// Emit a VCD waveform file from a sequential simulation result.
pub fn to_vcd(waveform: &Waveform) -> String {
    let mut out = String::new();
    out.push_str("$date\n    generated by frag\n$end\n");
    out.push_str("$version\n    frag tiny HDL compiler\n$end\n");
    out.push_str("$timescale 1ns $end\n");
    out.push_str(&format!("$scope module {} $end\n", waveform.module_name));

    let ids: BTreeMap<_, _> = waveform
        .names
        .iter()
        .enumerate()
        .map(|(idx, name)| (name.clone(), vcd_id(idx)))
        .collect();

    for name in &waveform.names {
        let width = waveform.widths.get(name).copied().unwrap_or(1);
        out.push_str(&format!(
            "$var wire {} {} {} $end\n",
            width,
            ids.get(name).expect("id exists"),
            name
        ));
    }

    out.push_str("$upscope $end\n");
    out.push_str("$enddefinitions $end\n");

    for tick in 0..waveform.ticks {
        out.push_str(&format!("#{}\n", tick));
        for name in &waveform.names {
            let width = waveform.widths.get(name).copied().unwrap_or(1);
            let values = waveform.values.get(name).expect("waveform value exists");
            let value = values.get(tick).copied().unwrap_or(0);
            let id = ids.get(name).expect("id exists");
            if width == 1 {
                out.push_str(&format!("{}{}\n", value & 1, id));
            } else {
                out.push_str(&format!("b{} {}\n", binary_string(value, width), id));
            }
        }
    }

    out
}

fn run_truth_table(module: &IrModule, options: &SimOptions) -> Result<TruthTable> {
    let inputs = signal_names(module, IrSignalKind::Input);
    let outputs = signal_names(module, IrSignalKind::Output);
    let total_input_width: u32 = module
        .signals
        .iter()
        .filter(|signal| signal.kind == IrSignalKind::Input)
        .map(|signal| signal.width)
        .sum();

    let combinations = if options.inputs.is_empty() && total_input_width <= 8 {
        1u128 << total_input_width
    } else {
        1
    };

    let mut rows = Vec::new();
    for combo in 0..combinations {
        let mut values = initial_values(module, &options.inputs)?;
        if options.inputs.is_empty() {
            apply_combo_inputs(module, combo, &mut values);
        }
        evaluate_combinational(module, &mut values);
        rows.push(values);
    }

    Ok(TruthTable {
        inputs,
        outputs,
        rows,
    })
}

fn run_waveform(module: &IrModule, options: &SimOptions) -> Result<Waveform> {
    let ticks = options.ticks.max(1);
    let mut values = initial_values(module, &options.inputs)?;
    let clocks = clock_names(module);
    let names = watched_names(module, &clocks);
    let widths = names
        .iter()
        .filter_map(|name| {
            module
                .signal(name)
                .map(|signal| (name.clone(), signal.width))
                .or_else(|| clocks.contains(name).then_some((name.clone(), 1)))
        })
        .collect::<BTreeMap<_, _>>();
    let mut traces = names
        .iter()
        .map(|name| (name.clone(), Vec::with_capacity(ticks)))
        .collect::<BTreeMap<_, _>>();

    for tick in 0..ticks {
        for clock in &clocks {
            values.insert(clock.clone(), (tick % 2) as u128);
        }

        evaluate_combinational(module, &mut values);
        for name in &names {
            let value = values.get(name).copied().unwrap_or(0);
            traces
                .get_mut(name)
                .expect("trace exists")
                .push(mask(value, *widths.get(name).unwrap_or(&1)));
        }

        let mut pending = BTreeMap::new();
        for process in &module.processes {
            let _edge = match process.edge {
                Edge::Rising => 1u8,
                Edge::Falling => 0u8,
            };
            for assignment in &process.assignments {
                let width = module
                    .signal(&assignment.target)
                    .map(|signal| signal.width)
                    .unwrap_or(128);
                let value = eval_expr(&assignment.expr, &values);
                pending.insert(assignment.target.clone(), mask(value, width));
            }
        }

        for (name, value) in pending {
            values.insert(name, value);
        }
    }

    Ok(Waveform {
        module_name: module.name.clone(),
        ticks,
        names,
        widths,
        values: traces,
    })
}

fn validate_inputs(module: &IrModule, inputs: &BTreeMap<String, u128>) -> Result<()> {
    for (name, value) in inputs {
        let signal = module.signal(name).ok_or_else(|| {
            Diagnostic::new(format!(
                "Input override references unknown signal `{}`",
                name
            ))
        })?;
        if signal.kind != IrSignalKind::Input {
            return Err(Diagnostic::new(format!(
                "Input override `{}` is a {}, not an input",
                name, signal.kind
            )));
        }
        if *value > mask(u128::MAX, signal.width) {
            return Err(Diagnostic::new(format!(
                "Input override `{}` value {} does not fit in {} bit(s)",
                name, value, signal.width
            )));
        }
    }
    Ok(())
}

fn initial_values(
    module: &IrModule,
    inputs: &BTreeMap<String, u128>,
) -> Result<BTreeMap<String, u128>> {
    let mut values = BTreeMap::new();
    for signal in &module.signals {
        values.insert(signal.name.clone(), 0);
    }

    for constant in &module.constants {
        let value = eval_expr(&constant.expr, &values);
        values.insert(constant.name.clone(), mask(value, constant.width));
    }

    for (name, value) in inputs {
        let signal = module
            .signal(name)
            .expect("input overrides are validated before simulation");
        values.insert(name.clone(), mask(*value, signal.width));
    }

    Ok(values)
}

fn apply_combo_inputs(module: &IrModule, combo: u128, values: &mut BTreeMap<String, u128>) {
    let mut shift = 0;
    for signal in module
        .signals
        .iter()
        .filter(|signal| signal.kind == IrSignalKind::Input)
    {
        let value = (combo >> shift) & mask(u128::MAX, signal.width);
        values.insert(signal.name.clone(), value);
        shift += signal.width;
    }
}

fn evaluate_combinational(module: &IrModule, values: &mut BTreeMap<String, u128>) {
    for constant in &module.constants {
        let value = eval_expr(&constant.expr, values);
        values.insert(constant.name.clone(), mask(value, constant.width));
    }

    for assignment in &module.combinational {
        let width = module
            .signal(&assignment.target)
            .map(|signal| signal.width)
            .unwrap_or(128);
        let value = eval_expr(&assignment.expr, values);
        values.insert(assignment.target.clone(), mask(value, width));
    }
}

fn eval_expr(expr: &Expr, values: &BTreeMap<String, u128>) -> u128 {
    match expr {
        Expr::Number { value, .. } => *value,
        Expr::Bool { value, .. } => (*value) as u128,
        Expr::Signal { name, .. } => values.get(name).copied().unwrap_or(0),
        Expr::Unary { op, expr, .. } => {
            let value = eval_expr(expr, values);
            match op {
                UnaryOp::LogicNot => (value == 0) as u128,
                UnaryOp::BitNot => !value,
                UnaryOp::Neg => 0u128.wrapping_sub(value),
            }
        }
        Expr::Binary {
            op, left, right, ..
        } => {
            let left = eval_expr(left, values);
            let right = eval_expr(right, values);
            match op {
                BinaryOp::Add => left.wrapping_add(right),
                BinaryOp::Sub => left.wrapping_sub(right),
                BinaryOp::Mul => left.wrapping_mul(right),
                BinaryOp::Div => left.checked_div(right).unwrap_or(0),
                BinaryOp::Mod => left.checked_rem(right).unwrap_or(0),
                BinaryOp::Shl => checked_shift(right)
                    .and_then(|shift| left.checked_shl(shift))
                    .unwrap_or(0),
                BinaryOp::Shr => checked_shift(right)
                    .and_then(|shift| left.checked_shr(shift))
                    .unwrap_or(0),
                BinaryOp::Lt => (left < right) as u128,
                BinaryOp::Le => (left <= right) as u128,
                BinaryOp::Gt => (left > right) as u128,
                BinaryOp::Ge => (left >= right) as u128,
                BinaryOp::Eq => (left == right) as u128,
                BinaryOp::Ne => (left != right) as u128,
                BinaryOp::BitAnd => left & right,
                BinaryOp::BitXor => left ^ right,
                BinaryOp::BitOr => left | right,
                BinaryOp::LogicAnd => ((left != 0) && (right != 0)) as u128,
                BinaryOp::LogicOr => ((left != 0) || (right != 0)) as u128,
            }
        }
        Expr::Conditional {
            condition,
            then_expr,
            else_expr,
            ..
        } => {
            if eval_expr(condition, values) != 0 {
                eval_expr(then_expr, values)
            } else {
                eval_expr(else_expr, values)
            }
        }
    }
}

fn checked_shift(value: u128) -> Option<u32> {
    u32::try_from(value).ok()
}

fn signal_names(module: &IrModule, kind: IrSignalKind) -> Vec<String> {
    module
        .signals
        .iter()
        .filter(|signal| signal.kind == kind)
        .map(|signal| signal.name.clone())
        .collect()
}

fn clock_names(module: &IrModule) -> BTreeSet<String> {
    module
        .processes
        .iter()
        .map(|process| process.clock.clone())
        .collect()
}

fn watched_names(module: &IrModule, clocks: &BTreeSet<String>) -> Vec<String> {
    let mut names = Vec::new();
    for clock in clocks {
        push_unique(&mut names, clock.clone());
    }
    for signal in &module.signals {
        if matches!(signal.kind, IrSignalKind::Output | IrSignalKind::Reg) {
            push_unique(&mut names, signal.name.clone());
        }
    }
    names
}

fn push_unique(values: &mut Vec<String>, value: String) {
    if !values.contains(&value) {
        values.push(value);
    }
}

fn mask(value: u128, width: u32) -> u128 {
    if width >= 128 {
        value
    } else {
        value & ((1u128 << width) - 1)
    }
}

fn binary_string(value: u128, width: u32) -> String {
    (0..width)
        .rev()
        .map(|bit| if ((value >> bit) & 1) == 1 { '1' } else { '0' })
        .collect()
}

fn vcd_id(idx: usize) -> String {
    let first = b'!' + (idx % 94) as u8;
    if idx < 94 {
        (first as char).to_string()
    } else {
        format!("{}{}", first as char, idx / 94)
    }
}

impl fmt::Display for SimulationResult {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            SimulationResult::TruthTable(table) => table.fmt(f),
            SimulationResult::Waveform(waveform) => waveform.fmt(f),
        }
    }
}

impl fmt::Display for TruthTable {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        if self.inputs.is_empty() && self.outputs.is_empty() {
            return writeln!(f, "No visible signals to simulate");
        }

        writeln!(
            f,
            "{}{}{}",
            self.inputs.join(" "),
            if self.inputs.is_empty() || self.outputs.is_empty() {
                ""
            } else {
                " | "
            },
            self.outputs.join(" ")
        )?;

        for row in &self.rows {
            let input_values = self
                .inputs
                .iter()
                .map(|name| row.get(name).copied().unwrap_or(0).to_string())
                .collect::<Vec<_>>()
                .join(" ");
            let output_values = self
                .outputs
                .iter()
                .map(|name| row.get(name).copied().unwrap_or(0).to_string())
                .collect::<Vec<_>>()
                .join(" ");
            writeln!(
                f,
                "{}{}{}",
                input_values,
                if input_values.is_empty() || output_values.is_empty() {
                    ""
                } else {
                    " | "
                },
                output_values
            )?;
        }

        Ok(())
    }
}

impl fmt::Display for Waveform {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        writeln!(f, "Simulation: {} ({} ticks)", self.module_name, self.ticks)?;
        for name in &self.names {
            let values = self.values.get(name).expect("trace exists");
            let width = self.widths.get(name).copied().unwrap_or(1);
            writeln!(f, "{}: {}", name, format_series(values, width))?;
        }
        Ok(())
    }
}

fn format_series(values: &[u128], width: u32) -> String {
    if width == 1 || values.iter().all(|value| *value < 10) {
        values
            .iter()
            .map(|value| value.to_string())
            .collect::<Vec<_>>()
            .join("")
    } else {
        values
            .iter()
            .map(|value| value.to_string())
            .collect::<Vec<_>>()
            .join(" ")
    }
}
